### ISSUE TITLE
A question about predicting sex

### ISSUE THREAD

**Issue by QianhuiWan** [schalkwyk/wateRmelon#6]
Dear Leonard Schalkwyk, 
I have a question about estimating sex, are we only use probes on X chromosomes, or probes on both X and Y chromosomes can be used? Thank you so much! 
Best regards
Qianhui

**Comment by yiluyucheng** [comment]
> Dear Leonard Schalkwyk,
> I have a question about estimating sex, are we only use probes on X chromosomes, or probes on both X and Y chromosomes can be used? Thank you so much!
> Best regards
> Qianhui

Hi Qianhui,
Thanks for your enquiry, I should apologize for the late reply, we used probes on both X and Y chromosomes to predict sex. If you have more questions in estimating sex by watermelon, please directly email yw19282@essex.ac.uk.
Yucheng

**Comment by QianhuiWan** [comment]
Thank you so much!
